config/routes.rb
Wap::Application.routes.draw do

  namespace :admin do
    resources :photos
    resources :mobile_types
    resources :software_types
    resources :softwares
    resources :downfiles
    
    match 'upload' => 'upload_resource#index'
   
  end

  root :to => 'wap#index'
  match '/admin' => 'admin/home#index'

  match 'software/:id' => 'wap#show'
  match 'softwares/:id' => 'wap#more'
  
  match 'login' => 'login#login'
  match 'logout' => 'login#logout'
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/downfile.rb
class Downfile < ActiveRecord::Base
end

app/models/login_user.rb
class LoginUser
  attr_accessor :username, :password
end

app/models/mobile_type.rb
class MobileType < ActiveRecord::Base
   has_and_belongs_to_many :softwares
end

app/models/photo.rb
class Photo < ActiveRecord::Base
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :resource_data, :polymorphic => true
  
  scope :images, where(:file_type => 'img')
  scope :softwares, where(:file_type => 'software')
  scope :free, where(:resource_data_id => nil)
  
  def self.icon
    where(:file_type => 'icon').first
  end  
end

app/models/software.rb
class Software < ActiveRecord::Base
  has_and_belongs_to_many :software_types
  has_and_belongs_to_many :mobile_types
  
  has_many :resources, :as => :resource_data, :dependent => :destroy
  accepts_nested_attributes_for :resources, :allow_destroy =>  true
  
end

app/models/software_type.rb
class SoftwareType < ActiveRecord::Base
  has_and_belongs_to_many :softwares
  
  belongs_to :parent, :class_name => "SoftwareType"
  has_many :children, :class_name => "SoftwareType", :foreign_key => :parent_id
end

app/models/upload_resource.rb
class UploadResource < ActiveRecord::Base
  belongs_to :resource_data, :polymorphic => true 
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ActionController::Base
  layout 'admin'
  protect_from_forgery
  
  
  before_filter :check_auth
 
  def check_auth
    if !session["login_user"]
      redirect_to '/login'
    end
  end  
  
  
end

app/controllers/admin/downfiles_controller.rb
class Admin::DownfilesController < Admin::AdminController
  # GET /downfiles
  # GET /downfiles.xml
  def index
    @downfiles = Downfile.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @downfiles }
    end
  end

  # GET /downfiles/1
  # GET /downfiles/1.xml
  def show
    @downfile = Downfile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @downfile }
    end
  end

  # GET /downfiles/new
  # GET /downfiles/new.xml
  def new
    @downfile = Downfile.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @downfile }
    end
  end

  # GET /downfiles/1/edit
  def edit
    @downfile = Downfile.find(params[:id])
  end

  # POST /downfiles
  # POST /downfiles.xml
  def create
    @downfile = Downfile.new(params[:downfile])

    respond_to do |format|
      if @downfile.save
        format.html { redirect_to(admin_downfile_path(@downfile), :notice => 'Downfile was successfully created.') }
        format.xml  { render :xml => @downfile, :status => :created, :location => @downfile }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @downfile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /downfiles/1
  # PUT /downfiles/1.xml
  def update
    @downfile = Downfile.find(params[:id])

    respond_to do |format|
      if @downfile.update_attributes(params[:downfile])
        format.html { redirect_to(admin_downfile_path(@downfile), :notice => 'Downfile was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @downfile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /downfiles/1
  # DELETE /downfiles/1.xml
  def destroy
    @downfile = Downfile.find(params[:id])
    @downfile.destroy

    respond_to do |format|
      format.html { redirect_to(admin_downfiles_path) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::AdminController
  def index
    check_auth
  end
  
  def check_auth
    if !session["login_user"]
      redirect_to '/login'
    end
  end
  
  def logout
    redirect_to :controller => '/login',  :action => 'logout'
  end
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < Admin::AdminController
  # GET /photos
  # GET /photos.xml
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.xml
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.xml
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.xml
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to(admin_photo_path(@photo), :notice => 'Photo was successfully created.') }
        format.xml  { render :xml => @photo, :status => :created, :location => @photo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.xml
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to(@photo, :notice => 'Photo was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.xml
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to(admin_photos_path) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def login
    if params[:username] && params[:password]
      if params[:username] == 'yz' && params[:password] == '303'
        session[:login_user] = 'yz'
        redirect_to '/'
      end
    end
  end
  def logout
    session[:login_user] = nil
    redirect_to :action => :login
  end
end

app/controllers/wap_controller.rb
class WapController < ApplicationController
  def index
      
  end
  
  def show
    
  end
end

app/helpers/admin/softwares_helper.rb
module Admin::SoftwaresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/downfiles_helper.rb
module DownfilesHelper
end

app/helpers/mobile_types_helper.rb
module MobileTypesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/software_types_helper.rb
module SoftwareTypesHelper
end

app/helpers/softwares_helper.rb
module SoftwaresHelper
end

app/views/admin/downfiles/_form.html.erb
<%= form_for([:admin,@downfile]) do |f| %>
  <% if @downfile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@downfile.errors.count, "error") %> prohibited this downfile from being saved:</h2>

      <ul>
      <% @downfile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :software_id %><br />
    <%= f.text_field :software_id %>
  </div>
  <div class="field">
    <%= f.label :file_name %><br />
    <%= f.text_field :file_name %>
  </div>
  <div class="field">
    <%= f.label :Platform %><br />
    <%= f.text_field :Platform %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/downfiles/edit.html.erb
<h1>Editing downfile</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_downfiles_path(@downfile) %> |
<%= link_to 'Back', admin_downfiles_path %>

app/views/admin/downfiles/index.html.erb
<h1>Listing downfiles</h1>

<table>
  <tr>
    <th>Software</th>
    <th>File name</th>
    <th>Platform</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @downfiles.each do |downfile| %>
  <tr>
    <td><%= downfile.software_id %></td>
    <td><%= downfile.file_name %></td>
    <td><%= downfile.Platform %></td>
    <td><%= link_to 'Show', admin_downfile_path(downfile) %></td>
    <td><%= link_to 'Edit', edit_admin_downfile_path(downfile) %></td>
    <td><%= link_to 'Destroy', admin_downfile_path(downfile), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Downfile', new_admin_downfile_path %>

app/views/admin/downfiles/new.html.erb
<h1>New downfile</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_downfiles_path %>

app/views/admin/downfiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Software:</b>
  <%= @downfile.software_id %>
</p>

<p>
  <b>File name:</b>
  <%= @downfile.file_name %>
</p>

<p>
  <b>Platform:</b>
  <%= @downfile.Platform %>
</p>


<%= link_to 'Edit', edit_admin_downfile_path(@downfile) %> |
<%= link_to 'Back', admin_downfiles_path %>

app/views/admin/photos/_form.html.erb
<%= form_for([:admin,@photo]) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :software_id %><br />
    <%= f.text_field :software_id %>
  </div>
  <div class="field">
    <%= f.label :photo_name %><br />
    <%= f.text_field :photo_name %>
  </div>
  <div class="field">
    <%= f.label :photo_type %><br />
    <%= f.text_field :photo_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_photos_path(@photo) %> |
<%= link_to 'Back', admin_photos_path %>

app/views/admin/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Software</th>
    <th>Photo name</th>
    <th>Photo type</th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.software_id %></td>
    <td><%= photo.photo_name %></td>
    <td><%= photo.photo_type %></td>
    <td><%= link_to 'Show', admin_photo_path(photo) %></td>
    <td><%= link_to 'Edit', edit_admin_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', admin_photo_path(photo), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_admin_photo_path %>

app/views/admin/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_photos_path %>

app/views/admin/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Software:</b>
  <%= @photo.software_id %>
</p>

<p>
  <b>Photo type:</b>
  <%= @photo.photo_name %>
</p>
<p>
  <b>Photo type:</b>
  <%= @photo.photo_type %>
</p>

<%= link_to 'Edit', edit_admin_photo_path(@photo) %> |
<%= link_to 'Back', admin_photos_path %>