config/routes.rb
Wap::Application.routes.draw do

  namespace :admin do
    resources :photos
    resources :mobile_types
    resources :software_types
    resources :softwares
    resources :downfiles
    
    match 'upload' => 'upload_resource#index'
   
  end

  root :to => 'wap#index'
  match '/admin' => 'admin/home#index'

  match 'software/:id' => 'wap#show'
  match 'softwares/:id' => 'wap#more'
  
  match 'login' => 'login#login'
  match 'logout' => 'login#logout'
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/downfile.rb
class Downfile < ActiveRecord::Base
end

app/models/login_user.rb
class LoginUser
  attr_accessor :username, :password
end

app/models/mobile_type.rb
class MobileType < ActiveRecord::Base
   has_and_belongs_to_many :softwares
end

app/models/photo.rb
class Photo < ActiveRecord::Base
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :resource_data, :polymorphic => true
  
  scope :images, where(:file_type => 'img')
  scope :softwares, where(:file_type => 'software')
  scope :free, where(:resource_data_id => nil)
  
  def self.icon
    where(:file_type => 'icon').first
  end  
end

app/models/software.rb
class Software < ActiveRecord::Base
  has_and_belongs_to_many :software_types
  has_and_belongs_to_many :mobile_types
  
  has_many :resources, :as => :resource_data, :dependent => :destroy
  accepts_nested_attributes_for :resources, :allow_destroy =>  true
  
end

app/models/software_type.rb
class SoftwareType < ActiveRecord::Base
  has_and_belongs_to_many :softwares
  
  belongs_to :parent, :class_name => "SoftwareType"
  has_many :children, :class_name => "SoftwareType", :foreign_key => :parent_id
end

app/models/upload_resource.rb
class UploadResource < ActiveRecord::Base
  belongs_to :resource_data, :polymorphic => true 
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ActionController::Base
  layout 'admin'
  protect_from_forgery
  
  
  before_filter :check_auth
 
  def check_auth
    if !session["login_user"]
      redirect_to '/login'
    end
  end  
  
  
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::AdminController
  def index
    check_auth
  end
  
  def check_auth
    if !session["login_user"]
      redirect_to '/login'
    end
  end
  
  def logout
    redirect_to :controller => '/login',  :action => 'logout'
  end
end

app/controllers/admin/software_types_controller.rb
class Admin::SoftwareTypesController < Admin::AdminController
  # GET /software_types
  # GET /software_types.xml
  def index
    @software_types = SoftwareType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @software_types }
    end
  end

  # GET /software_types/1
  # GET /software_types/1.xml
  def show
    @software_type = SoftwareType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @software_type }
    end
  end

  # GET /software_types/new
  # GET /software_types/new.xml
  def new
    @software_type = SoftwareType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @software_type }
    end
  end

  # GET /software_types/1/edit
  def edit
    @software_type = SoftwareType.find(params[:id])
  end

  # POST /software_types
  # POST /software_types.xml
  def create
    @software_type = SoftwareType.new(params[:software_type])

    respond_to do |format|
      if @software_type.save
        format.html { redirect_to( admin_software_type_path(@software_type), :notice => 'Software type was successfully created.') }
        format.xml  { render :xml => @software_type, :status => :created, :location => @software_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @software_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /software_types/1
  # PUT /software_types/1.xml
  def update
    @software_type = SoftwareType.find(params[:id])

    respond_to do |format|
      if @software_type.update_attributes(params[:software_type])
        format.html { redirect_to(admin_software_type_path(@software_type), :notice => 'Software type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @software_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /software_types/1
  # DELETE /software_types/1.xml
  def destroy
    @software_type = SoftwareType.find(params[:id])
    @software_type.destroy

    respond_to do |format|
      format.html { redirect_to(admin_software_types_path) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def login
    if params[:username] && params[:password]
      if params[:username] == 'yz' && params[:password] == '303'
        session[:login_user] = 'yz'
        redirect_to '/'
      end
    end
  end
  def logout
    session[:login_user] = nil
    redirect_to :action => :login
  end
end

app/controllers/wap_controller.rb
class WapController < ApplicationController
  def index
      
  end
  
  def show
    
  end
end

app/helpers/admin/softwares_helper.rb
module Admin::SoftwaresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/downfiles_helper.rb
module DownfilesHelper
end

app/helpers/mobile_types_helper.rb
module MobileTypesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/software_types_helper.rb
module SoftwareTypesHelper
end

app/helpers/softwares_helper.rb
module SoftwaresHelper
end

app/views/admin/software_types/_form.html.erb
<%= form_for([:admin, @software_type]) do |f| %>
  <% if @software_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@software_type.errors.count, "error") %> prohibited this software_type from being saved:</h2>

      <ul>
      <% @software_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/software_types/edit.html.erb
<h1>Editing software_type</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_software_type_path(@software_type) %> |
<%= link_to 'Back', admin_software_types_path %>

app/views/admin/software_types/index.html.erb
<h1>Listing software_types</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @software_types.each do |software_type| %>
  <tr>
    <td><%= software_type.title %></td>
    <td><%= software_type.status %></td>
    <td><%= link_to 'Show', admin_software_type_path(software_type) %></td>
    <td><%= link_to 'Edit', edit_admin_software_type_path(software_type) %></td>
    <td><%= link_to 'Destroy', admin_software_type_path(software_type), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Software type', new_admin_software_type_path %>

app/views/admin/software_types/new.html.erb
<h1>New software_type</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_software_types_path %>

app/views/admin/software_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @software_type.title %>
</p>

<p>
  <b>Status:</b>
  <%= @software_type.status %>
</p>


<%= link_to 'Edit', edit_admin_software_type_path(@software_type) %> |
<%= link_to 'Back', admin_software_types_path %>