config/routes.rb
Wap::Application.routes.draw do

  namespace :admin do
    resources :photos
    resources :mobile_types
    resources :software_types
    resources :softwares
    resources :downfiles
    
    match 'upload' => 'upload_resource#index'
   
  end

  root :to => 'wap#index'
  match '/admin' => 'admin/home#index'

  match 'software/:id' => 'wap#show'
  match 'softwares/:id' => 'wap#more'
  
  match 'login' => 'login#login'
  match 'logout' => 'login#logout'
end

app/models/software.rb
class Software < ActiveRecord::Base
  has_and_belongs_to_many :software_types
  has_and_belongs_to_many :mobile_types
  
  has_many :resources, :as => :resource_data, :dependent => :destroy
  accepts_nested_attributes_for :resources, :allow_destroy =>  true
  
end

app/models/software_type.rb
class SoftwareType < ActiveRecord::Base
  has_and_belongs_to_many :softwares
  
  belongs_to :parent, :class_name => "SoftwareType"
  has_many :children, :class_name => "SoftwareType", :foreign_key => :parent_id
end

app/controllers/admin/softwares_controller.rb
class Admin::SoftwaresController < Admin::AdminController
  # GET /softwares
  # GET /softwares.xml
  def index
    @softwares = Software.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @softwares }
    end
  end

  # GET /softwares/1
  # GET /softwares/1.xml
  def show
    @software = Software.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @software }
    end
  end

  # GET /softwares/new
  # GET /softwares/new.xml
  def new
    @software = Software.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @software }
    end
  end

  # GET /softwares/1/edit
  def edit
    @software = Software.find(params[:id])
  end

  # POST /softwares
  # POST /softwares.xml
  def create
    @software = Software.new(params[:software])

    respond_to do |format|
      if @software.save
        format.html { redirect_to(admin_software_path(@software), :notice => 'Software was successfully created.') }
        format.xml  { render :xml => @software, :status => :created, :location => @software }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @software.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /softwares/1
  # PUT /softwares/1.xml
  def update
    @software = Software.find(params[:id])
    if params[:datafile]
      r = Resource.new
      r.original_filename = params[:datafile].original_filename
      r.file_type = params[:file_type]
      r.ext = File.extname(r.original_filename)
      r.save
      directory = "public/upload/" + r.file_type
      path = File.join(directory, r.id.to_s + r.ext)
      
      File.open(path, "wb") { |f| f.write(params[:datafile].read) }
      @software.resources << r
     # render :text => "File has been uploaded successfully "
    end
    respond_to do |format|
      if @software.update_attributes(params[:software])
        format.html { redirect_to(admin_software_path(@software), :notice => 'Software was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @software.errors, :status => :unprocessable_entity }
      end
    end
    
  end

  # DELETE /softwares/1
  # DELETE /softwares/1.xml
  def destroy
    @software = Software.find(params[:id])
    @software.destroy

    respond_to do |format|
      format.html { redirect_to(admin_softwares_path) }
      format.xml  { head :ok }
    end
  end
  
  
end

app/helpers/admin/softwares_helper.rb
module Admin::SoftwaresHelper
end

app/helpers/softwares_helper.rb
module SoftwaresHelper
end

app/views/admin/softwares/_form.html.erb
<% current_ids = @software.software_type_ids %>
<%= form_for([:admin,@software], :html => {:multipart => true}) do |f| %>
  <% if @software.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@software.errors.count, "error") %> prohibited this software from being saved:</h2>
      <ul>
      <% @software.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.text_field :language %>
  </div> 
  
   <div>
	<%= f.label :mobiletype %><br />
  	<% MobileType.all.each do |mt| %>
    	<label><%= mt.title %>
      		<%= check_box_tag "software[mobile_type_ids][]", mt.id, current_ids.include?(mt.id) %>
    	</label>
  	<% end %>	
</div>  

  <div>
	<%= f.label :softwaretype %><br />
  	<% SoftwareType.all.each do |st| %>
    	<label><%= st.title %>
      		<%= check_box_tag "software[software_type_ids][]", st.id, current_ids.include?(st.id) %>
    	</label>
  	<% end %>	
  	
</div>
<div>
	Images:
	<% @software.resources.images.each do |img| %>
		<label><%= img.original_filename %></label>
	<% end %><br />
	
	<% Resource.images.free.order(:original_filename).each do |img| %>

	<%= image_tag "/upload/#{img.file_type}/#{img.id}#{img.ext}", :width => 30 %>

		<label><%= img.id %><%= img.ext%></label>
		
		<%= check_box_tag "software[resource_ids][]", img.id, false %>
		<br />
	<% end %>
</div>
<div>
	Softwares:
	<% @software.resources.softwares.each do |img| %>
		<label><%= img.original_filename %></label>
	<% end %>
	<br />
	<% Resource.softwares.free.order(:original_filename).each do |img| %>
		<label><%= img.original_filename %></label>
		<%= check_box_tag "software[resource_ids][]", img.id, false %>
	<% end %>
</div>
  <br />
  
  <div>
    <label for="file">Upload:</label>
         文件：<%= file_field_tag "datafile" %>属性：
    <%= select_tag("file_type", "<option>img</option><option>software</option><option>icon</option>".html_safe) %>

  </div>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/softwares/edit.html.erb
<h1>Editing admin_software</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_software_path(@software) %> |
<%= link_to 'Back', admin_softwares_path %>

app/views/admin/softwares/index.html.erb
<h1>Listing softwares</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th>Title</th>
    <th>Language</th>
  </tr>

<% @softwares.each do |software| %>
  <tr>
  	 <td><%= link_to 'Show', admin_software_path(software) %></td>
    <td><%= link_to 'Edit', edit_admin_software_path(software) %></td>
    <td><%= link_to 'Destroy', admin_software_path(software), :confirm => 'Are you sure?', :method => :delete %></td>

    <td><%= software.title %></td>
    <td><%= software.language %></td>
     </tr>
<% end %>
</table>

<br />

<%= link_to 'New Software', new_admin_software_path %>

app/views/admin/softwares/new.html.erb
<h1>New software</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_softwares_path %>

app/views/admin/softwares/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @software.title %>
</p>

<p>
  <b>Description:</b>
  <%= @software.description %>
</p>

<p>
  <b>Language:</b>
  <%= @software.language %>
</p>


<%= link_to 'Edit', edit_admin_software_path(@software) %> |
<%= link_to 'Back', admin_softwares_path %>